default:
  image: jezcope/erambler-nikola:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - date -Iseconds
    - nikola version
    - nikola build
  artifacts:
    paths:
      - public
  only:
    - master
