baseurl: https://erambler.co.uk/
title: eRambler
copyright: "(c) 2016 Jez Cope — [CC-BY-SA](/license/)"

languageCode: en-GB
metaDataFormat: yaml
rssuri: feed.xml

ignoreFiles: ["^\\.#"]

theme: sidmouth

disqusShortname: erambler

permalinks:
  post: '/blog/:slug/'
  page: '/:slug/'

taxonomies:
  tag: tags
  topic: topics

author:
  name: Jez Cope

params:
  home: home
  brand: a blog about
  topline: |
    [research communication](/topics/research-communication/)
    <span class="amp">&</span> [higher education](/topics/higher-education)
    <span class="amp">&</span> [technology](/topics/technology/)
    <span class="amp">&</span> [librarianship](/topics/librarianship/)
    <span class="amp">&</span> [stuff](/topics/stuff/)
  footline: 'brought to you by [hugo](http://gohugo.io/)'
  
  googleAnalytics: UA-10201101-1

  github: jezcope
  twitter: jezcope
  linkedin: jezcope
  wercker: eabedc12f9bc4c2e496bb85791b4207b

  sidebar: left

  highlight: solarized_light
...
