baseurl: http://erambler.co.uk/
title: eRambler
copyright: "(c) 2016 Jez Cope — [CC-BY-SA](/license/)"

languageCode: en-GB
metaDataFormat: yaml

ignoreFiles: ["^\\.#"]

theme: sidmouth

disqusShortname: erambler

permalinks:
  post: '/blog/:slug/'
  page: '/:slug/'

taxonomies:
  tag: tags

author:
  name: Jez Cope

params:
  home: home
  brand: a blog about
  topline: 'research communication + higher education + technology + stuff'
  footline: 'brought to you by [hugo](http://gohugo.io/)'
  
  github: jezcope
  twitter: jezcope
  linkedin: jezcope

  sidebar: left
...
